### ISSUE TITLE
ModuleNotFoundError: No module named 'typeid'

### ISSUE THREAD

**Issue by wuzimi** [yoheinakajima/mindgraph#3]
C:\Users\Administrator\Documents\GitHub\mindgraph>python main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\mindgraph\main.py", line 1, in <module>
    from app import create_app
  File "C:\Users\Administrator\Documents\GitHub\mindgraph\app\__init__.py", line 23, in <module>
    from .integrations.database import CurrentDBIntegration
  File "C:\Users\Administrator\Documents\GitHub\mindgraph\app\integrations\database\__init__.py", line 4, in <module>
    from .nexus import NexusDBIntegration
  File "C:\Users\Administrator\Documents\GitHub\mindgraph\app\integrations\database\nexus.py", line 15, in <module>
    from typeid import TypeID, get_prefix_and_suffix as typeid_prefix
ModuleNotFoundError: No module named 'typeid'

**Comment by jerlinn** [comment]
Try `pip install typeid-python nexus_python`, it works.

**Comment by feraranas** [comment]
The project is using Poetry for dependency management, since it has a ```pyproject.toml``` file.

So, to install the missing typeid module using Poetry:
- ensure you have poetry installed
- run ```poetry install``` . This will install all the required packages

this will create a virtual environment for the project, so now run:
- ```poetry run python main.py```

**Comment by wuzimi** [comment]
Thanks guys! It works now.

**Comment by simpleusername96** [comment]
> The project is using Poetry for dependency management, since it has a `pyproject.toml` file.
> 
> So, to install the missing typeid module using Poetry:
> 
> * ensure you have poetry installed
> * run `poetry install` . This will install all the required packages
> 
> this will create a virtual environment for the project, so now run:
> 
> * `poetry run python main.py`

i'm getting this message after this
`Current Python version (3.11.3) is not allowed by the project (>=3.10.0,<3.11).`

guess i'd just have to use python3.10

**Comment by feraranas** [comment]
> > The project is using Poetry for dependency management, since it has a `pyproject.toml` file.
> > So, to install the missing typeid module using Poetry:
> > 
> > * ensure you have poetry installed
> > * run `poetry install` . This will install all the required packages
> > 
> > this will create a virtual environment for the project, so now run:
> > 
> > * `poetry run python main.py`
> 
> i'm getting this message after this `Current Python version (3.11.3) is not allowed by the project (>=3.10.0,<3.11).`
> 
> guess i'd just have to use python3.10

Also, if you run into other dependency errors run ```poetry add <name_of_dependency>```

**Comment by simpleusername96** [comment]
i had to do 'poetry add beautifulsoup4', eventhough beautifulsoup4 was in [tool.poetry.dependencies] under pyproject.toml

**Comment by solvaholic** [comment]
> guess i'd just have to use python3.10

:+1: See also https://github.com/yoheinakajima/mindgraph/issues/12 about that requirement.

> Thanks guys! It works now.

@wuzimi Since this is resolved, would you close the issue? :bow:
